#!/usr/bin/env node
/**
 * Bundle the embeddable widget and produce TWO outputs:
 *
 *   1. frontend/public/widget.js                       (static file, optional)
 *   2. frontend/app/api/widget/widget-bundle.ts        (embedded in Next.js bundle)
 *
 * The TypeScript file is the one that actually matters in production —
 * an API route serves its contents at /widget.js via a Vercel rewrite.
 * This bypasses Vercel's static file pipeline entirely, which has been
 * unreliable for this particular file.
 */
const path = require("path");
const fs = require("fs");

const ENTRY = path.resolve(__dirname, "..", "..", "widget", "src", "widget.ts");
const PUBLIC_DIR = path.resolve(__dirname, "..", "public");
const PUBLIC_OUT = path.join(PUBLIC_DIR, "widget.js");
const BUNDLE_TS_DIR = path.resolve(__dirname, "..", "app", "api", "widget");
const BUNDLE_TS = path.join(BUNDLE_TS_DIR, "widget-bundle.ts");

async function main() {
  console.log("──▶ Building embeddable widget");

  if (!fs.existsSync(ENTRY)) {
    console.error("✗ Widget source not found at: " + ENTRY);
    process.exit(1);
  }

  let esbuild;
  try {
    esbuild = require("esbuild");
  } catch (e) {
    console.error("✗ esbuild is not installed in frontend/devDependencies");
    process.exit(1);
  }

  fs.mkdirSync(PUBLIC_DIR, { recursive: true });
  fs.mkdirSync(BUNDLE_TS_DIR, { recursive: true });

  console.log("──▶ Bundling " + path.relative(process.cwd(), ENTRY));
  const t0 = Date.now();

  await esbuild.build({
    entryPoints: [ENTRY],
    bundle: true,
    minify: true,
    sourcemap: false,
    platform: "browser",
    target: "es2018",
    outfile: PUBLIC_OUT,
    legalComments: "none",
    logLevel: "warning",
  });

  const code = fs.readFileSync(PUBLIC_OUT, "utf-8");
  const size = code.length;

  // Emit the TypeScript bundle file (this is what Vercel actually serves)
  const tsContent =
    `// AUTO-GENERATED by frontend/scripts/build-widget.js — do not edit.\n` +
    `// Built from widget/src/widget.ts at ${new Date().toISOString()}\n` +
    `export const WIDGET_JS = ${JSON.stringify(code)};\n` +
    `export const WIDGET_SIZE = ${size};\n`;
  fs.writeFileSync(BUNDLE_TS, tsContent);

  console.log(`✓ widget.js published (${(size / 1024).toFixed(1)} KB) in ${Date.now() - t0}ms`);
  console.log(`  Static: ${path.relative(process.cwd(), PUBLIC_OUT)}`);
  console.log(`  Embed:  ${path.relative(process.cwd(), BUNDLE_TS)}`);
  console.log("  Will be served at: /widget.js via /api/widget rewrite\n");
}

main().catch((err) => {
  console.error("Widget build error:", err);
  process.exit(1);
});
